# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hallgato/KMP/projectmunka/projectmunka.srcs/sources_1/ip/clk_65mhz/clk_65mhz.xci
# IP: The module: 'clk_65mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hallgato/KMP/projectmunka/projectmunka.srcs/sources_1/ip/clk_65mhz/clk_65mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hallgato/KMP/projectmunka/projectmunka.srcs/sources_1/ip/clk_65mhz/clk_65mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hallgato/KMP/projectmunka/projectmunka.srcs/sources_1/ip/clk_65mhz/clk_65mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/hallgato/KMP/projectmunka/projectmunka.srcs/sources_1/ip/clk_65mhz/clk_65mhz.xci
# IP: The module: 'clk_65mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hallgato/KMP/projectmunka/projectmunka.srcs/sources_1/ip/clk_65mhz/clk_65mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hallgato/KMP/projectmunka/projectmunka.srcs/sources_1/ip/clk_65mhz/clk_65mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hallgato/KMP/projectmunka/projectmunka.srcs/sources_1/ip/clk_65mhz/clk_65mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
