# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/hallgato/KMP/Nexys-4-DDR-Master.xdc

# IP: ip/fold/fold.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fold || ORIG_REF_NAME==fold} -quiet] -quiet

# IP: ip/loons/loons.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==loons || ORIG_REF_NAME==loons} -quiet] -quiet
